#!/usr/bin/python3
#

import datetime
from sys import stderr
import os

steam_path = '/usr/bin/steam'
now = datetime.datetime.now()
if now.hour >= 9 and now.hour <= 17 and now.weekday() < 5:          # Saturday = 5, Sunday = 6
    print("No Steam during work hours!", file=stderr)
    exit(os.EX_NOPERM)
else:
    os.execl(steam_path, "steam") # raises exception on failure

