#!/usr/bin/python
#
# First Python program
# 2017-10-18 MJD

import subprocess
import sys
  
def main():
  if len(sys.argv) != 3:
    usage();

  key_id, key_file = sys.argv[1:3]
  while True:
    try:
      output = subprocess.check_output(["ssh-add", "-l"])
    except subprocess.CalledProcessError:
      output = ""

    if key_id.find(output) :
      break
    subprocess.call(["ssh-add", key_file])

def usage():
  print >> sys.stderr, "Usage: %s key-id key-file" % sys.argv[0]
  exit(1)

main()
  
