#!/usr/bin/python
#
# First Python program
# 2017-10-18 MJD

import subprocess
import sys
  
def main():
  key_id, key_file = sys.argv[1:3]
  while True:
    try:
      output = subprocess.check_output(["ssh-add", "-l"])
    except subprocess.CalledProcessError:
      output = ""

    if key_id.find(output) :
      break
    subprocess.call(["ssh-add", key_file])

main()
  
